version: 2
jobs:
  unit-test:
    parallelism: 2
    working_directory: ~/nomad
    docker:
      - image: omnyway/ci-base:${CI_BASE_VERSION}
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      - LEIN_ROOT: nbd
      - SERVICE_NAME: nomad
      - AWS_PROFILE: staging
    steps:
      - checkout
      - run: /omnypay-ci/set-aws-creds.sh
      - restore_cache:
          keys:
            - lein-deps-{{ checksum "project.clj" }}
      - run: AWS_PROFILE=staging lein deps
      - save_cache:
          key: lein-deps-{{ checksum "project.clj" }}
          paths:
            - /root/.m2
            - /root/.lein
      - run: AWS_PROFILE=staging lein test
  release:
    parallelism: 1
    working_directory: ~/nomad
    docker:
      - image: omnyway/ci-base:${CI_BASE_VERSION}
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      - LEIN_ROOT: nbd
      - VERSION_FILE: ../VERSION
      - SERVICE_NAME: nomad
      - GOROOT: ""
      - GOPATH: "/root/.go"
      - AWS_PROFILE: staging
    steps:
      - checkout
      - run: /omnypay-ci/set-aws-creds.sh
      - restore_cache:
          keys:
            - lein-deps-{{ checksum "project.clj" }}
      - run: AWS_PROFILE=staging lein deps
      - save_cache:
          key: lein-deps-{{ checksum "project.clj" }}
          paths:
            - /root/.m2
            - /root/.lein
      - run: semver-from-git $VERSION_FILE
      - run: SEMVER=$(cat $VERSION_FILE) /omnypay-ci/release-lib.sh
workflows:
  version: 2
  build_test_release:
    jobs:
      - unit-test
      - release:
          requires:
            - unit-test
          filters:
            branches:
              only: master
