version: 2
jobs:
  unit-test:
    parallelism: 1
    working_directory: ~/nomad
    docker:
      - image: circleci/clojure:latest
      - image: postgres:9.6.2
    environment:
      - SERVICE_NAME: nomad
      - PGPASSWD: postgres
    steps:
      - checkout
      - run: git clone https://${READ_BOT_TOKEN}@github.com/omnypay/omnypay-ci.git  ~/omnypay-ci
      - run: ~/omnypay-ci/install-basic-deps.sh
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
      - run: sudo apt-get install -yy bc
      - run: clojure -Atest unit
      - save_cache:
          key: deps-{{ checksum "deps.edn" }}
          paths:
            - ~/.m2
            - ~/.gitlibs
  release:
    parallelism: 1
    working_directory: ~/nomad
    docker:
      - image: circleci/clojure:latest
    environment:
      - LEIN_ROOT: nbd
      - VERSION_FILE: ../VERSION
      - SERVICE_NAME: nomad
      - GOROOT: ""
      - GOPATH: "/root/.go"
      - AWS_PROFILE: staging
    steps:
      - checkout
      - run: git clone https://${READ_BOT_TOKEN}@github.com/omnypay/omnypay-ci.git  ~/omnypay-ci
      - run: ~/omnypay-ci/install-basic-deps.sh
      - run: ~/omnypay-ci/install-release-deps.sh
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
      - run: semver-from-git $VERSION_FILE
      - run: export SEMVER=$(cat $VERSION_FILE); ~/omnypay-ci/release-lib.sh
workflows:
  version: 2
  build_test_release:
    jobs:
      - unit-test
      - release:
          requires:
            - unit-test
          filters:
            branches:
              only: master
